# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Reuses rollout from crash (add crash to path when running)
_target_: rollout.GeoTransolverOneShot
_convert_: all

functional_dim: 3
out_dim: 250
geometry_dim: 3
global_dim: null
slice_num: 128
n_layers: 6
use_te: false
time_input: false
include_local_features: true

num_time_steps: ${training.num_time_steps}
