from parser import parse_args
from print_and_save import print_and_save_results
from benchmark import end_to_end_benchmark
from measure_perf import benchmark_model
from measure_memory import get_model_memory_usage