# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Writer-layout and backward-read tests for the ``.pmsh`` memmap format.

``golden_pmsh/`` contains an immutable decorator-era fixture and a fixture
written by the current ``TensorClass`` implementation. Both must reconstruct
an exact :class:`~physicsnemo.mesh.Mesh`; the current fixture also serves as a
golden manifest for the writer layout.

To intentionally update the current writer layout, run
``test/mesh/mesh/golden_pmsh/_regenerate.py`` and commit the new fixture
without replacing the legacy fixture.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest
import torch

from physicsnemo.mesh.mesh import Mesh

### Locate the regeneration helper without requiring `golden_pmsh` to be a package.
### A missing helper is a hard error rather than a skip: these fixtures are the
### only thing pinning the on-disk format, so losing them silently would drop
### the coverage this module exists to provide.
_REGEN_PATH = Path(__file__).parent / "golden_pmsh" / "_regenerate.py"
assert _REGEN_PATH.is_file(), f"Missing .pmsh regeneration helper: {_REGEN_PATH}"
_spec = importlib.util.spec_from_file_location("_pmsh_golden_regen", _REGEN_PATH)
assert _spec is not None and _spec.loader is not None
_regen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_regen)
build_canonical_mesh = _regen.build_canonical_mesh
CURRENT_FIXTURE_DIR: Path = _regen.CURRENT_FIXTURE_DIR
LEGACY_FIXTURE_DIR: Path = _regen.LEGACY_FIXTURE_DIR


@pytest.fixture(
    params=(CURRENT_FIXTURE_DIR, LEGACY_FIXTURE_DIR),
    ids=("current-tensorclass", "legacy-decorator"),
)
def fixture_dir(request: pytest.FixtureRequest) -> Path:
    """Return each committed layout, failing clearly if one was removed."""
    path: Path = request.param
    assert path.is_dir(), f"Missing committed .pmsh fixture: {path}"
    return path


class TestPmshGoldenFixture:
    """Load a committed ``.pmsh`` fixture and verify field-by-field equality."""

    def test_reconstructs_exact_mesh_type(self, fixture_dir: Path):
        """Both layouts reconstruct the structured type, not a TensorDict."""
        loaded = Mesh.load(fixture_dir)
        assert type(loaded) is Mesh

    def test_geometry_matches(self, fixture_dir: Path):
        """`points` and `cells` round-trip exactly."""
        loaded = Mesh.load(fixture_dir)
        expected = build_canonical_mesh()
        assert loaded.n_points == expected.n_points
        assert loaded.n_cells == expected.n_cells
        assert loaded.n_spatial_dims == expected.n_spatial_dims
        assert loaded.n_manifold_dims == expected.n_manifold_dims
        assert torch.equal(loaded.points, expected.points)
        assert torch.equal(loaded.cells, expected.cells)

    def test_data_fields_match(self, fixture_dir: Path):
        """Every key in `point_data`, `cell_data`, `global_data` round-trips exactly."""
        loaded = Mesh.load(fixture_dir)
        expected = build_canonical_mesh()
        for field in ("point_data", "cell_data", "global_data"):
            loaded_td = getattr(loaded, field)
            expected_td = getattr(expected, field)
            assert set(loaded_td.keys()) == set(expected_td.keys()), (
                f"{field} key mismatch: "
                f"loaded={sorted(loaded_td.keys())}, "
                f"expected={sorted(expected_td.keys())}"
            )
            for key in expected_td.keys():
                assert torch.equal(loaded_td[key], expected_td[key]), (
                    f"{field}[{key!r}] value mismatch after load"
                )

    def test_current_writer_layout_matches_fixture(
        self, tmp_path: Path, serialization_manifest
    ):
        """A fresh save has the committed current directory and metadata layout."""
        written = tmp_path / "current.pmsh"
        build_canonical_mesh().save(written)
        assert serialization_manifest(written) == serialization_manifest(
            CURRENT_FIXTURE_DIR
        )

    def test_legacy_fixture_keeps_the_decorator_layout(self):
        """The legacy fixture must never be regenerated by current code.

        The decorator-era writer nested the payload under ``_tensordict/``;
        the current one writes it at the root. Without this check,
        regenerating the legacy fixture would leave two current-format
        fixtures, and the backward-read coverage would vanish silently.
        """
        assert (LEGACY_FIXTURE_DIR / "_tensordict").is_dir()
        assert not (CURRENT_FIXTURE_DIR / "_tensordict").exists()

    @pytest.mark.cuda
    def test_load_honors_device(self, fixture_dir: Path):
        """``device=`` applies to both layouts, not just the current one."""
        loaded = Mesh.load(fixture_dir, device="cuda")
        assert loaded.points.device.type == "cuda"
        assert loaded.cells.device.type == "cuda"
        assert loaded.point_data.device.type == "cuda"
